[package]
name = "omg_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = "0.3"
serde = "1.0"
serde_json = "1.0"
tokio ={ version = "1", default-features = false, features = ["sync"]}