[package]
name = "omg_sqlite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
omg_core = { path = "../omg_core" }
time = "0.3"
serde_json = "1.0"
sqlite = "0.32.0"