[package]
name = "sync_demo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
omg_core = { path = "../omg_core" }
omg_sqlite = { path = "../omg_sqlite" }
serde = "1.0"
serde_json = "1.0"